FROM python:3.9-slim
WORKDIR /app
COPY . /app
RUN pip install --no-cache-dir -r requirements.txt
EXPOSE 5002
ENV FLASK_APP=random_number_service.py
CMD ["flask", "run", "--host=0.0.0.0", "--port=5002"]
